image: alpine/edge
packages:
  - mdbook
  - rsync
secrets:
  - 377b1655-4b5b-43a9-8cee-e48808fd7e55
environment:
  deploy: build@alias-asso.fr
sources:
  - https://git.sr.ht/~alias/student-docs#main
tasks:
  - build: |
      cd student-docs
      mdbook build
  - deploy: |
      if [ $BUILD_SUBMITTER != "git.sr.ht" ]; then
          echo "Skipping deploy for non-git.sr.ht build"
          exit
      fi
      cd student-docs
      sshopts="ssh -o StrictHostKeyChecking=no"
      rsync --rsh="$sshopts" -avh --delete book/ $deploy:/var/www/docs.alias-asso.fr/
