[book]
authors = ["Alias"]
language = "fr"
multilingual = false
src = "src"
title = "Documentation Alias"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
no-section-label = true
git-repository-url = "https://sr.ht/~alias/docs.alias-asso.fr/"
git-repository-icon = "fa-git"
mathjax-support = true
